Repository grafana/faro-web-sdk, pull requests merged in 2023-12, with the labels that each got.

#421 Custom-session-id-generator
  CHANGELOG.md
  packages/core/src/config/types.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Labels: feature

#420 User defined attributes are missing in the session meta
  CHANGELOG.md
  packages/core/src/config/types.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Labels: bug

#428 fix: remove storage sync between browser contexts.
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
Labels: bug

#431 feat: disable `keepalive` if body size is >= 60 kb
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/transport.test.ts
  experimental/transport-otlp-http/src/transport.ts
Labels: enhancement

#436 fix: fix the check for presence of Event
  CHANGELOG.md
  packages/core/src/utils/is.ts
Labels: enhancement

#438 FetchTransport: make sessionId retrieval more stable
  packages/web-sdk/src/transports/fetch/transport.ts
Labels: enhancement
