Repository grafana/faro-web-sdk, pull requests merged in 2023-05, with the labels that each got.

#173 docker-compose: fix grafana-agent path
  docker-compose.yaml
Labels: bug

#172 Update quick-start-browser.md
  docs/sources/tutorials/quick-start-browser.md
Labels: Q1SE

#190 add additional error context to excceptions API
  CHANGELOG.md
  experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  packages/core/README.md
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/exceptions/types.ts
Labels: feature

#191 fix: add correct span_id and add context to log
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toEventLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toLogLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toMeasurementLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  experimental/transport-otlp-http/src/transport.test.ts
Labels: bug
