Repository grafana/faro-web-sdk, pull requests merged in 2024-06, with the labels that each got.

#595 Add web vitals with attribution instrumentation
  CHANGELOG.md
  demo/src/client/faro/initialize.ts
  packages/core/src/config/types.ts
  packages/web-sdk/package.json
  packages/web-sdk/src/config/makeCoreConfig.ts
  packages/web-sdk/src/instrumentations/instrumentationConstants.ts
  packages/web-sdk/src/instrumentations/performance/navigation.test.ts
  packages/web-sdk/src/instrumentations/performance/navigation.ts
  packages/web-sdk/src/instrumentations/performance/performanceConstants.ts
  packages/web-sdk/src/instrumentations/webVitals/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/webVitals/instrumentation.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsBasic.test.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsBasic.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsWithAttribution.test.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsWithAttribution.ts
  yarn.lock
Labels: feature

#617 fix: mark peer deps `react-dom` and `react-router-dom` as optional
  CHANGELOG.md
  packages/react/package.json
Labels: dependencies, enhancement

#621 chore(deps): upgrade otel in web-tracing, faro core and faro demo
  CHANGELOG.md
  demo/package.json
  demo/src/server/otel/initialize.ts
  docs/sources/tutorials/quick-start-browser.md
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  packages/core/package.json
  packages/web-tracing/package.json
  packages/web-tracing/src/getDefaultOTELInstrumentations.ts
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/types.ts
  yarn.lock
Labels: dependencies

#622 feat: add helper functions to initialize React Router integration
  CHANGELOG.md
  packages/react/README.md
  packages/react/src/index.ts
  packages/react/src/router/index.ts
  packages/react/src/router/v4v5/index.ts
  packages/react/src/router/v4v5/initialize.ts
  packages/react/src/router/v6/index.ts
  packages/react/src/router/v6/initialize.ts
Labels: enhancement
