Repository grafana/faro-web-sdk, pull requests merged in 2024-01, with the labels that each got.

#437 430 add body field for measurement logs for otlp transport
  experimental/transport-otlp-http/README.md
  experimental/transport-otlp-http/src/payload/OtelPayload.test.ts
  experimental/transport-otlp-http/src/payload/OtelPayload.ts
  experimental/transport-otlp-http/src/payload/transform/index.ts
  experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toMeasurementLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  experimental/transport-otlp-http/src/payload/transform/types.ts
  experimental/transport-otlp-http/src/transport.ts
  experimental/transport-otlp-http/src/types.ts
Labels: enhancement

#448 Fix-demo
  CHANGELOG.md
  Dockerfile
  demo/src/client/faro/initialize.ts
Labels: bug, Demo App

#450 fix: patch demo for arm64
  docker-compose.yaml
Labels: dependencies, enhancement

#434 Faro navigation and resource metrics part 1
  CHANGELOG.md
  cypress/e2e/demo/errors.cy.ts
  cypress/e2e/demo/events.cy.ts
  cypress/e2e/demo/logs.cy.ts
  cypress/e2e/demo/measurements.cy.ts
  demo/src/client/faro/initialize.ts
  packages/web-sdk/src/config/getWebInstrumentations.ts
  packages/web-sdk/src/config/types.ts
  packages/web-sdk/src/index.ts
  packages/web-sdk/src/instrumentations/index.ts
  packages/web-sdk/src/instrumentations/performance/index.ts
  packages/web-sdk/src/instrumentations/performance/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/performance/instrumentation.ts
  packages/web-sdk/src/instrumentations/performance/navigation.test.ts
  packages/web-sdk/src/instrumentations/performance/navigation.ts
  packages/web-sdk/src/instrumentations/performance/performanceConstants.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtilsTestData.ts
  packages/web-sdk/src/instrumentations/performance/resource.test.ts
  packages/web-sdk/src/instrumentations/performance/resource.ts
  packages/web-sdk/src/instrumentations/performance/types.ts
  packages/web-sdk/src/metas/session/createSession.ts
Labels: feature, enhancement

#467 chore: bump @opentelemetry/instrumentation-document-load dependency to ^0.35.0
  CHANGELOG.md
  packages/web-tracing/package.json
  yarn.lock
Labels: dependencies
