Repository grafana/faro-web-sdk, pull requests merged in 2024-02, with the labels that each got.

#475 fix: update all OTel dependencies
  CHANGELOG.md
  demo/package.json
  packages/core/package.json
  packages/web-tracing/package.json
  yarn.lock
Labels: dependencies

#490 Add resource load duration
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/performance/navigation.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/performance/types.ts
Labels: bug, enhancement

#494 fix: crash when navigator.userAgentData is undefined
  CHANGELOG.md
  packages/web-sdk/src/metas/browser/meta.ts
Labels: bug

#482 feat: enable performance timeline by default
  CHANGELOG.md
  packages/web-sdk/src/config/getWebInstrumentations.ts
  packages/web-sdk/src/config/types.ts
Labels: feature

#499 480 create opentelemetry trace sampler taking faro sampling decisions into account
  CHANGELOG.md
  packages/web-tracing/jest.config.js
  packages/web-tracing/package.json
  packages/web-tracing/src/faroTraceExporter.ts
  packages/web-tracing/src/faroTraceExporter.utils.test.ts
  packages/web-tracing/src/faroTraceExporter.utils.ts
  packages/web-tracing/src/index.ts
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/sampler.test.ts
  packages/web-tracing/src/sampler.ts
Labels: enhancement
