Repository grafana/faro-web-sdk, pull requests merged in 2024-05, with the labels that each got.

#581 fix: fixing import of Patterns in web tracing package
  CHANGELOG.md
  packages/web-tracing/src/types.ts
Labels: bug

#585 Faro react type issues create routes from children
  demo/package.json
  packages/react/README.md
  packages/react/src/router/v6/types.ts
  yarn.lock
Labels: bug

#476 source map upload SDK changes
  CHANGELOG.md
  packages/core/src/api/exceptions/types.ts
  packages/core/src/metas/registerInitial.ts
  packages/core/src/metas/types.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/sourceMaps.test.ts
  packages/core/src/utils/sourceMaps.ts
Labels: feature

#594 Track window dimensions
  CHANGELOG.md
  docs/sources/developer/architecture/components/metas.md
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/payload/transform/toResourceLog.test.ts
  experimental/transport-otlp-http/src/payload/transform/toResourceSpan.test.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  packages/core/src/metas/types.ts
  packages/web-sdk/src/metas/browser/meta.ts
Labels: feature

#591 590 grafana cloud create new session if 400 session invalid is returned
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionConstants.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/types.ts
  packages/web-sdk/src/transports/fetch/transport.test.ts
  packages/web-sdk/src/transports/fetch/transport.ts
Labels: enhancement

#589 feat(web-sdk): forward logArgsSerializer in initializeFaro to the core
  CHANGELOG.md
  packages/core/src/api/index.ts
  packages/core/src/api/logs/const.ts
  packages/core/src/api/logs/index.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/index.ts
  packages/web-sdk/src/config/makeCoreConfig.test.ts
  packages/web-sdk/src/config/makeCoreConfig.ts
Labels: enhancement
