Repository grafana/faro-web-sdk, pull requests merged in 2024-03, with the labels that each got.

#513 512 session manager started timestamp is reset on page load aka session resume
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Labels: bug

#510 Add span context when sending faro events which belong to specific spans
  CHANGELOG.md
  packages/core/src/api/events/initialize.test.ts
  packages/core/src/api/events/initialize.ts
  packages/core/src/api/events/types.ts
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/exceptions/types.ts
  packages/core/src/api/logs/initialize.test.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/logs/types.ts
  packages/core/src/api/measurements/initialize.test.ts
  packages/core/src/api/measurements/initialize.ts
  packages/core/src/api/measurements/types.ts
  packages/web-tracing/src/faroTraceExporter.utils.test.ts
  packages/web-tracing/src/faroTraceExporter.utils.ts
Labels: bug

#519 fix: infinite loop if session dom storage is turned off
  CHANGELOG.md
  demo/src/client/faro/initialize.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Labels: bug

#518 235 faroroutes support for routerprovider react router v6
  CHANGELOG.md
  demo/src/client/faro/initialize.ts
  packages/react/README.md
  packages/react/src/index.ts
  packages/react/src/router/index.ts
  packages/react/src/router/initialize.ts
  packages/react/src/router/types.ts
  packages/react/src/router/v6/FaroRoutes.tsx
  packages/react/src/router/v6/index.ts
  packages/react/src/router/v6/initialize.ts
  packages/react/src/router/v6/routerDependencies.ts
  packages/react/src/router/v6/types.ts
  packages/react/src/router/v6/withFaroRouterInstrumentation.ts
  packages/react/src/types.ts
Labels: feature

#526 Feat: Add responseStatus to performance events
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtilsTestData.ts
  packages/web-sdk/src/instrumentations/performance/types.ts
Labels: enhancement

#528 chore(docs): Update Faro-React docs, add upgrade instructions
  packages/react/README.md
Labels: type/docs

#530 chore(docs): add releases section
  README.md
Labels: type/docs

#531 feat(k6): add testRunId to k6 meta if available in k6 object
  docs/sources/developer/architecture/components/metas.md
  packages/core/src/metas/types.ts
  packages/web-sdk/src/config/makeCoreConfig.test.ts
  packages/web-sdk/src/metas/k6/meta.ts
Labels: feature

#536 chore(sessions): remove structured clone
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
Labels: enhancement
