Repository grafana/faro-web-sdk, pull requests merged in 2024-11, with the labels that each got.

#720 chore: Fix links in the GOVERNANCE.md
  GOVERNANCE.md
Labels: type/docs

#730 fix(console instrumentation): handle circular object references in json parser for console.error
  CHANGELOG.md
  cypress/e2e/demo/errors.cy.ts
  cypress/e2e/demo/logs.cy.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
  packages/web-sdk/src/utils/index.ts
  packages/web-sdk/src/utils/json.test.ts
  packages/web-sdk/src/utils/json.ts
Labels: bug

#731 refactor(ConsoleInstrumentation): Provide config option to send log messages for console.error calls
  CHANGELOG.md
  packages/core/src/config/types.ts
  packages/web-sdk/src/config/makeCoreConfig.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.ts
  packages/web-sdk/src/instrumentations/console/types.ts
Labels: improvement

#733 chore(deps): update to latest version
  .prettierignore
  demo/package.json
  lerna.json
  package.json
  yarn.lock
Labels: dependencies

#739 chore(deps-dev): pin tough cookie version
  package.json
Labels: dependencies

#742 fix(ConsoleInstrumentation): guard json stringifier for non-error logs agains circular references
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/console/instrumentation.ts
Labels: bug

#745 fix(console instrumentation): revert to former log parsing behavior
  packages/web-sdk/src/instrumentations/console/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.ts
Labels: bug

#746 chore(release): prepare 1.12.2
  CHANGELOG.md
Labels: release

#747 chore(deps): upgrade grafana/eslint-config to fix security alert
  package.json
  yarn.lock
Labels: dependencies
