Repository grafana/faro-web-sdk, pull requests merged in 2024-08, with the labels that each got.

#658 652 navigation timing is off set
  CHANGELOG.md
  packages/core/src/api/events/initialize.test.ts
  packages/core/src/api/events/initialize.ts
  packages/core/src/api/events/types.ts
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/exceptions/types.ts
  packages/core/src/api/logs/initialize.test.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/logs/types.ts
  packages/core/src/api/measurements/initialize.test.ts
  packages/core/src/api/measurements/initialize.ts
  packages/core/src/api/measurements/types.ts
  packages/core/src/utils/date.ts
  packages/core/src/utils/getCurrentTimestamp.ts
  packages/core/src/utils/index.ts
  packages/web-sdk/src/instrumentations/performance/navigation.test.ts
  packages/web-sdk/src/instrumentations/performance/navigation.ts
  packages/web-sdk/src/instrumentations/performance/resource.test.ts
  packages/web-sdk/src/instrumentations/performance/resource.ts
Labels: bug, enhancement

#659 chore(web-tracing): ignore network events by default
  CHANGELOG.md
  packages/web-tracing/src/getDefaultInstrumentations.test.ts
  packages/web-tracing/src/getDefaultOTELInstrumentations.ts
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/types.ts
Labels: change

#661 Update use-angular.md, Add etWebInstrumentations import
  docs/sources/tutorials/use-angular.md
Labels: type/docs

#664 chore(otlp-http-transport): consume response body
  CHANGELOG.md
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/transport.test.ts
  experimental/transport-otlp-http/src/transport.ts
Labels: bug

#665 changelog
  CHANGELOG.md
  experimental/CHANGELOG.md
Labels: release
