Repository grafana/faro-web-sdk, pull requests merged in 2025-02, with the labels that each got.

#932 chore(release): prepare v1.13.0
  CHANGELOG.md
Labels: release

#934 chore(release): v1.13.1
  CHANGELOG.md
Labels: release

#944 fix: add error context attributes stringifier
  CHANGELOG.md
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/index.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/json.test.ts
  packages/core/src/utils/json.ts
Labels: bug

#951 chore(release): v1.13.2
  CHANGELOG.md
Labels: release

#952 chore: transform all properties in `context` and `attributes` objects to string
  CHANGELOG.md
  packages/core/src/api/events/initialize.test.ts
  packages/core/src/api/events/initialize.ts
  packages/core/src/api/logs/initialize.test.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/measurements/initialize.test.ts
  packages/core/src/api/measurements/initialize.ts
  packages/core/src/utils/json.test.ts
Labels: improvement

#981 feat: adding ability to track all changes for web vitals
  CHANGELOG.md
  packages/core/src/config/types.ts
  packages/web-sdk/src/config/makeCoreConfig.test.ts
  packages/web-sdk/src/config/makeCoreConfig.ts
  packages/web-sdk/src/instrumentations/webVitals/instrumentation.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsBasic.ts
  packages/web-sdk/src/instrumentations/webVitals/webVitalsWithAttribution.ts
Labels: improvement

#928 chore(web-tracing): remove zone-context-manager
  CHANGELOG.md
  packages/web-tracing/package.json
  packages/web-tracing/src/instrumentation.ts
  yarn.lock
Labels: improvement, breaking

#999 chore(release): prepare release 1.14
  CHANGELOG.md
Labels: release

#1008 chore(release): prepare 1.14.1
  CHANGELOG.md
Labels: release
