Repository grafana/faro-web-sdk, pull requests merged in 2025-04, with the labels that each got.

#1089 chore: don't add empty context or attribute objects if no data is provided
  CHANGELOG.md
  packages/core/src/api/events/initialize.test.ts
  packages/core/src/api/events/initialize.ts
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/logs/initialize.test.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/logs/types.ts
  packages/core/src/api/measurements/initialize.test.ts
  packages/core/src/api/measurements/initialize.ts
  packages/web-sdk/src/instrumentations/errors/getErrorDetails.test.ts
Labels: improvement

#1095 chore: update changelog
  CHANGELOG.md
Labels: release

#1100 fix: url parser for xhr requests didn't check for toString
  CHANGELOG.md
  packages/web-sdk/src/index.ts
  packages/web-sdk/src/instrumentations/userActions/httpRequestMonitor.ts
  packages/web-sdk/src/utils/index.ts
  packages/web-sdk/src/utils/url.ts
  packages/web-sdk/src/utils/urls.test.ts
  packages/web-tracing/src/faroXhrInstrumentation.ts
  packages/web-tracing/src/getDefaultOTELInstrumentations.test.ts
Labels: bug

#1092 chore(deps): upgrade to TS5x
  CHANGELOG.md
  experimental/instrumentation-xhr/src/instrumentation.ts
  experimental/transport-otlp-http/src/payload/OtelPayload.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  experimental/transport-otlp-http/src/transport.ts
  package.json
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/measurements/initialize.ts
  packages/core/src/api/traces/initialize.ts
  packages/core/src/utils/is.ts
  packages/react/src/router/v6/withFaroRouterInstrumentation.ts
  packages/web-sdk/src/instrumentations/console/instrumentation.ts
  packages/web-sdk/src/instrumentations/errors/registerOnunhandledrejection.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
  packages/web-sdk/src/instrumentations/view/instrumentation.ts
  packages/web-sdk/src/transports/fetch/transport.ts
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/instrumentationUtils.ts
  tsconfig.base.cjs.json
  tsconfig.base.json
  yarn.lock
Labels: dependencies

#1101 chore: User action update durations
  CHANGELOG.md
  demo/src/client/faro/initialize.ts
  packages/core/src/api/const.ts
  packages/core/src/api/events/initialize.test.ts
  packages/core/src/api/events/initialize.ts
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/index.ts
  packages/core/src/api/logs/initialize.test.ts
  packages/core/src/api/logs/initialize.ts
  packages/core/src/api/measurements/initialize.test.ts
  packages/core/src/api/measurements/initialize.ts
  packages/core/src/api/types.ts
  packages/core/src/api/userActionLifecycleHandler.test.ts
  packages/core/src/api/userActionLifecycleHandler.ts
  packages/core/src/index.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/reactive.test.ts
  packages/core/src/utils/reactive.ts
  packages/web-sdk/src/index.ts
  packages/web-sdk/src/instrumentations/userActions/const.ts
  packages/web-sdk/src/instrumentations/userActions/httpRequestMonitor.test.ts
  packages/web-sdk/src/instrumentations/userActions/httpRequestMonitor.ts
  packages/web-sdk/src/instrumentations/userActions/index.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.test.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
  packages/web-sdk/src/instrumentations/userActions/types.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.ts
Labels: improvement

#1109 chore(changelog): update
  CHANGELOG.md
Labels: type/docs

#1111 chore(release): prepare 1.15.0
  CHANGELOG.md
Labels: type/docs, release

#1115 chore(User actions): provide function to start an action
  CHANGELOG.md
  demo/src/client/pages/Features/TracingInstrumentation.tsx
  packages/web-sdk/src/index.ts
  packages/web-sdk/src/instrumentations/index.ts
  packages/web-sdk/src/instrumentations/userActions/index.ts
  packages/web-sdk/src/instrumentations/userActions/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/userActions/instrumentation.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.test.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
  packages/web-sdk/src/instrumentations/userActions/types.ts
Labels: improvement

#1122 chore: manage milestones automatically
  .github/workflows/manage-milestones.yml
Labels: github_actions

#1126 chore(deps): bump otel to v0.200
  CHANGELOG.md
  demo/package.json
  demo/src/server/otel/initialize.ts
  experimental/transport-otlp-http/package.json
  experimental/transport-otlp-http/src/payload/transform/toErrorLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toEventLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toLogLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/toMeasurementLogRecord.test.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  experimental/transport-otlp-http/src/payload/transform/types.ts
  experimental/transport-otlp-http/src/semconv.ts
  packages/core/package.json
  packages/web-tracing/package.json
  packages/web-tracing/src/faroMetaAttributesSpanProcessor.ts
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/semconv.ts
  packages/web-tracing/src/sessionSpanProcessor.ts
  packages/web-tracing/src/types.ts
  yarn.lock
Labels: dependencies

#1133 chore(error tracking): provide original error to beforeSend hook
  CHANGELOG.md
  packages/core/src/api/exceptions/index.ts
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/exceptions/types.ts
  packages/core/src/api/index.ts
  packages/core/src/config/types.ts
  packages/core/src/index.ts
  packages/core/src/transports/initialize.ts
  packages/core/src/transports/transports.test.ts
  packages/web-sdk/src/config/makeCoreConfig.ts
  packages/web-sdk/src/index.ts
Labels: improvement

#1136 chore(release): prepare 1.16
  CHANGELOG.md
Labels: release

#1140 fix(faro-react): re-export the ExceptionEventExtended type
  CHANGELOG.md
  packages/react/src/index.ts
Labels: bug

#1139 fix(web-tracing): no Faro events for HTTP requests in CDN bundle
  CHANGELOG.md
  packages/web-sdk/src/index.ts
  packages/web-tracing/src/faroTraceExporter.utils.test.ts
  packages/web-tracing/src/faroTraceExporter.utils.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.ts
  packages/web-tracing/src/types.ts
Labels: bug

#1154 chore(resource-timings): guard against negative values
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
Labels: improvement

#1156 fix(resource timings): tlsNegotiationTime was wrong
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtilsTestData.ts
Labels: bug

#1155 chore(release): prepare 1.17.2
  CHANGELOG.md
Labels: release

#1170 fix(zizmor findings): tackle errors
  .github/workflows/commands.yml
  .github/workflows/manage-milestones.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/semantic-pr.yml
Labels: improvement, security, github_actions

#1171 chore(gh-actions): move secrets to vault
  .github/commands.json
  .github/workflows/commands.yml
  .github/workflows/dependabot-automerge.yml
  .github/workflows/release.yml
  .github/workflows/semantic-pr.yml
Labels: security, github_actions

#1172 fix(github actions): validate semantic pull request title
  .github/workflows/semantic-pr.yml
Labels: github_actions

#1168 fix(ignoreErrors): ensure to match on the original error and not on the parsed error
  CHANGELOG.md
  packages/core/src/api/exceptions/initialize.test.ts
  packages/core/src/api/exceptions/initialize.ts
  packages/core/src/api/exceptions/types.ts
  packages/core/src/transports/transports.test.ts
  packages/web-sdk/src/instrumentations/errors/registerOnerror.test.ts
  packages/web-sdk/src/instrumentations/errors/registerOnerror.ts
Labels: bug
