Repository grafana/faro-web-sdk, pull requests merged in 2025-01, with the labels that each got.

#827 fix(transport-otlp-http): don't send payload if endpoint URL is empty
  CHANGELOG.md
  experimental/CHANGELOG.md
  experimental/transport-otlp-http/src/transport.test.ts
  experimental/transport-otlp-http/src/transport.ts
Labels: bug

#763 fix: bump otel
  demo/package.json
  experimental/transport-otlp-http/package.json
  experimental/transport-otlp-http/src/payload/attribute/attributeUtils.ts
  experimental/transport-otlp-http/src/payload/transform/transform.ts
  experimental/transport-otlp-http/src/payload/transform/types.ts
  packages/core/package.json
  packages/core/src/api/traces/types.ts
  packages/core/src/transports/utils.test.ts
  packages/core/src/transports/utils.ts
  packages/web-sdk/package.json
  packages/web-tracing/jest.config.js
  packages/web-tracing/package.json
  packages/web-tracing/setup.jest.ts
  packages/web-tracing/src/faroTraceExporter.ts
  packages/web-tracing/src/faroTraceExporter.utils.ts
  tsconfig.base.json
  tsconfig.base.spec.json
  yarn.lock
Labels: dependencies

#860 chore(deps): upgrade @opentelemetry/otlp-transformer to 0.57.1
  experimental/transport-otlp-http/package.json
  packages/core/package.json
  packages/web-tracing/package.json
  yarn.lock
Labels: dependencies

#877 chore(release): prepare 1.12.3
  CHANGELOG.md
Labels: release

#893 feat: provide dynamic service name overrides
  demo/src/client/faro/initialize.ts
  experimental/transport-otlp-http/src/transport.test.ts
  packages/core/src/api/meta/initialize.ts
  packages/core/src/api/meta/initilialize.test.ts
  packages/core/src/api/meta/types.ts
  packages/core/src/index.ts
  packages/core/src/metas/index.ts
  packages/core/src/metas/types.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/is.test.ts
  packages/core/src/utils/is.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/PersistentSessionsManager.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionManager.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/VolatileSessionsManager.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
  packages/web-sdk/src/utils/webStorage.test.ts
  packages/web-sdk/src/utils/webStorage.ts
Labels: feature

#903 chore(overrides): send event when a service.name override happens
  CHANGELOG.md
  packages/core/src/index.ts
  packages/core/src/semantic.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.test.ts
  packages/web-sdk/src/instrumentations/session/instrumentation.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.test.ts
  packages/web-sdk/src/instrumentations/session/sessionManager/sessionManagerUtils.ts
Labels: bug, feature

#912 chore(demo): pin postgres version in docker compose
  docker-compose.yaml
Labels: Demo App

#914 chore: use Faro globalObject instead of window object
  experimental/instrumentation-fetch/src/instrumentation.test.ts
  experimental/instrumentation-fetch/src/instrumentation.ts
  experimental/instrumentation-xhr/src/instrumentation.test.ts
  experimental/instrumentation-xhr/src/instrumentation.ts
  packages/web-sdk/src/instrumentations/errors/registerOnerror.test.ts
  packages/web-sdk/src/instrumentations/errors/registerOnerror.ts
  packages/web-sdk/src/instrumentations/errors/registerOnunhandledrejection.ts
  packages/web-sdk/src/metas/browser/meta.ts
Labels: improvement
