Repository grafana/faro-web-sdk, pull requests merged in 2025-05, with the labels that each got.

#1169 chore(PerformanceInstrumentation): track transfer size
  CHANGELOG.md
  packages/web-sdk/src/instrumentations/performance/performanceUtils.test.ts
  packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  packages/web-sdk/src/instrumentations/performance/types.ts
Labels: improvement

#1180 chore(deps): update Node version support to satisfy EoL of Node18
  .github/workflows/pull-request.yml
  .nvmrc
  CHANGELOG.md
  demo/package.json
  experimental/instrumentation-fetch/package.json
  experimental/instrumentation-performance-timeline/package.json
  experimental/instrumentation-xhr/package.json
  experimental/transport-otlp-http/package.json
  package.json
  packages/core/package.json
  packages/react/package.json
  packages/web-sdk/package.json
  packages/web-tracing/package.json
Labels: dependencies, github_actions

#1181 chore(release): prepare v1.18.0
  CHANGELOG.md
Labels: release

#1183 chore(web-tracing): add resource attrs. for browser and distribution
  packages/web-tracing/src/instrumentation.ts
  packages/web-tracing/src/semconv.ts
Labels: improvement

#1217 chore(ci): delete milestones action
  .github/workflows/manage-milestones.yml
Labels: github_actions

#1215 chore: adding zizmor config
  .github/zizmor.yml
Labels: github_actions

#1259 chore(deps): remove node 18 support, add node 24 support
  .github/workflows/pull-request.yml
  README.md
  demo/package.json
  experimental/instrumentation-fetch/package.json
  experimental/instrumentation-performance-timeline/package.json
  experimental/instrumentation-xhr/package.json
  experimental/transport-otlp-http/package.json
  package.json
  packages/core/package.json
  packages/react/package.json
  packages/web-sdk/package.json
  packages/web-tracing/package.json
Labels: dependencies

#1249 chore(user actions): don't attach user action context to http request when in halt mode
  packages/web-sdk/src/index.ts
  packages/web-sdk/src/instrumentations/userActions/processUserActionEventHandler.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.test.ts
  packages/web-tracing/src/faroUserActionSpanProcessor.ts
Labels: bug

#1263 chore(release): prepare 1.18.2
  CHANGELOG.md
Labels: release
